import type { DreamWrite } from '@/types/Dream';

export const initialDreamsSeed: DreamWrite[] = [
    {
        date: '2026-08-01',
        title: 'Заброшенный город и управляемый полет',
        description:
            'Летал над заброшенным мегаполисом. В какой-то момент понял, что это сон, и попробовал управлять высотой и направлением полета. Потоки ветра ощущались очень реально.',
        categories: ['lucid'],
        categoryDetails: {
            lucid: {
                controlLevel: 8,
                trigger: 'anomaly',
            },
        },
        phenomena: ['flying'],
        phenomenaDetails: {
            flying: {
                type: 'effortless',
                altitude: 'cloud_level',
            },
        },
        quality: 8,
        clarity: 9,
        moodAfter: 9,
        timeOfDay: 'night',
        visualStyle: 'vivid',
        perspective: 'first_person',
        roles: ['protagonist'],
        sensations: ['sounds', 'tactile', 'kinesthetic'],
        characters: ['Незнакомец в черном'],
        locations: ['Заброшенный город', 'Небо'],
        objects: ['Высотки', 'Разрушенный мост'],
        emotions: ['Восторг', 'Свобода', 'Спокойствие'],

        PreSleepContext: 'Пил вечером крепкий мате и читал перед сном.',
        interpretations: [
            {
                tag: 'Полет',
                meaning:
                    'Стремление вырваться из повседневной рутины или чувство контроля над ситуацией.',
                sourceId: 'base_guide',
                isAccurate: true,
            },
        ],
        personalNotes: 'Нужно попробовать в следующий раз в ОС вызвать конкретного человека.',
        isFavorite: true,
        isPinned: true,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-03',
        title: 'Бесконечный лабиринт школьных коридоров',
        description:
            'Снова оказался в своей старой школе, но коридоры бесконечно петляли и меняли форму. Пытался найти кабинет для сдачи экзамена, но двери вели в тупики.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 7,
                copingMechanism: 'Проснулся от резкого звука будильника',
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['falling'],
        phenomenaDetails: {
            falling: {
                origin: 'stumbling',
                outcome: 'hypnic_jerk',
            },
        },
        quality: 4,
        clarity: 6,
        moodAfter: 3,
        timeOfDay: 'night',
        visualStyle: 'monochrome',
        perspective: 'first_person',
        roles: ['victim'],
        sensations: ['sounds', 'breathing'],
        characters: ['Учитель математики', 'Одноклассники'],
        locations: ['Школа', 'Темный коридор'],
        objects: ['Закрытая дверь', 'Часы'],
        emotions: ['Тревога', 'Страх', 'Растерянность'],

        PreSleepContext: 'Тяжелый рабочий день, переживал из-за дедлайна.',
        relatedDreams: [
            {
                relationType: 'recurring_instance',
                note: 'Повторяющийся сюжет с заплутанием в школе со времен учебы.',
            },
        ],
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-05',
        title: 'Разговор у старого маяка',
        description:
            'Сидели на краю обрыва возле старого маяка и слушали шум прибоя. Запах соли и резкий морской ветер ощущались абсолютно физически.',
        categories: ['prophetic'],
        categoryDetails: {
            prophetic: {
                expectedByDate: '2026-09-01',
                isFulfilled: false,
            },
        },
        quality: 9,
        clarity: 10,
        moodAfter: 8,
        timeOfDay: 'morning',
        visualStyle: 'color',
        perspective: 'first_person',
        roles: ['protagonist', 'observer'],
        sensations: ['sounds', 'smells', 'tactile', 'temperature'],
        characters: ['Старик-смотритель'],
        locations: ['Маяк', 'Морское побережье'],
        objects: ['Фонарь', 'Деревянная скамья'],
        emotions: ['Умиротворение', 'Ностальгия'],

        interpretations: [
            {
                tag: 'Маяк',
                meaning: 'Поиск верного пути или ориентира в важной жизненной ситуации.',
                sourceId: 'custom',
                isAccurate: null,
            },
        ],
        relatedDreams: [
            {
                dreamId: 1,
                relationType: 'similar_theme',
                note: 'Похожее чувство пространства и свободы, как при полете.',
            },
        ],
        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-06',
        title: 'Затерянная библиотека и перевернутое время',
        description:
            'Ходил по многоэтажной библиотеке, где вместо лестниц были парящие деревянные ступени. В центре зала стояли песочные часы высотой с дом, и песок в них сыпался вверх.',
        categories: [],
        phenomena: ['nested_dream'],
        phenomenaDetails: {
            nestedDream: {
                nestingLevels: 2,
            },
        },
        quality: 7,
        clarity: 8,
        moodAfter: 7,
        timeOfDay: 'night',
        visualStyle: 'color',
        perspective: 'third_person',
        roles: ['observer', 'camera_operator'],
        sensations: ['sounds', 'vision_anomaly'],
        characters: ['Библиотекарь в маске'],
        locations: ['Древняя библиотека', 'Парящие лестницы'],
        objects: ['Старинные фолианты', 'Песочные часы'],
        emotions: ['Любопытство', 'Удивление'],

        PreSleepContext: 'Слушал фоновую эмбиент-музыку перед сном.',
        interpretations: [
            {
                tag: 'Часы',
                meaning: 'Осознание ценности времени или переживания о нехватке ресурса.',
                sourceId: 'base_guide',
            },
        ],
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-07',
        title: 'Погоня в неоновом дождливом городе',
        description:
            'Убегал от странных теней по узким улочкам неонового сити в стиле киберпанка. Мокрый асфальт отражал вывески, а в конце переулка я сорвался с крыши.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 8,
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['falling', 'death'],
        phenomenaDetails: {
            falling: {
                origin: 'building_or_cliff',
                outcome: 'impact',
            },
            death: {
                cause: 'fall',
                aftermath: 'woke_up',
            },
        },
        quality: 5,
        clarity: 7,
        moodAfter: 4,
        timeOfDay: 'night',
        visualStyle: 'vivid',
        perspective: 'first_person',
        roles: ['victim'],
        sensations: ['sounds', 'tactile', 'pain'],
        characters: ['Теневые силуэты'],
        locations: ['Неоновый город', 'Темные переулки'],
        objects: ['Затопленные лужи', 'Яркие вывески'],
        emotions: ['Напряжение', 'Азарт', 'Страх'],

        PreSleepContext: 'Поздно заснул после просмотра нуарного фильма.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-08',
        title: 'Подводный сад и светящиеся рыбы',
        description:
            'Плавательное погружение без акваланга. Мог свободно дышать под водой. Вокруг цвели гигантские подводные растения, а мелкие рыбы светились бирюзовым светом при прикосновении.',
        categories: ['lucid'],
        categoryDetails: {
            lucid: {
                controlLevel: 6,
                trigger: 'spontaneous',
            },
        },
        quality: 10,
        clarity: 9,
        moodAfter: 10,
        timeOfDay: 'morning',
        visualStyle: 'vivid',
        perspective: 'first_person',
        roles: ['protagonist'],
        sensations: ['tactile', 'breathing', 'temperature'],
        characters: [],
        locations: ['Подводный сад', 'Океанское дно'],
        objects: ['Светящиеся водоросли', 'Коралловый риф'],
        emotions: ['Восторг', 'Спокойствие', 'Гармония'],

        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-08',
        title: 'Ночной поезд сквозь заснеженное поле',
        description:
            'Ехал в поезде, который двигался без рельсов прямо по заснеженной пустыне. За окном мелькали редкие одинокие фонари. Было полное ощущение отсутствия собственного тела.',
        categories: [],
        quality: 6,
        clarity: 5,
        moodAfter: 5,
        timeOfDay: 'day',
        visualStyle: 'dark',
        perspective: 'first_person',
        roles: ['disembodied'],
        sensations: ['sounds', 'temperature'],
        characters: ['Пассажир напротив'],
        locations: ['Купе поезда', 'Заснеженное поле'],
        objects: ['Стакан в подстаканнике', 'Фонарь'],
        emotions: ['Одиночество', 'Задумчивость'],

        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: true,
        isPrivate: true,
    },
    {
        date: '2026-08-09',
        title: 'Тень у кровати и скованность',
        description:
            'Проснулся от ощущения, что не могу шевельнуть ни рукой, ни ногой. В углу комнаты стоял темный силуэт, слышался гулкий шепот над самым ухом.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 9,
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['paralysis'],
        phenomenaDetails: {
            paralysis: {
                timing: 'waking_up',
                hallucinations: ['auditory', 'presence'],
            },
        },
        quality: 3,
        clarity: 8,
        moodAfter: 3,
        timeOfDay: 'morning',
        visualStyle: 'dark',
        perspective: 'first_person',
        roles: ['victim'],
        sensations: ['sounds', 'speech_voice', 'tactile'],
        characters: ['Теневая фигура'],
        locations: ['Спальня'],
        objects: ['Кровать', 'Окно'],
        emotions: ['Паника', 'Оцепенение'],

        PreSleepContext: 'Спал на спине, переутомился за день.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    {
        date: '2026-08-01',
        title: 'Заброшенный город и управляемый полет',
        description:
            'Летал над заброшенным мегаполисом. В какой-то момент понял, что это сон, и попробовал управлять высотой и направлением полета. Потоки ветра ощущались очень реально.',
        categories: ['lucid'],
        categoryDetails: {
            lucid: {
                controlLevel: 8,
                trigger: 'anomaly',
            },
        },
        phenomena: ['flying'],
        phenomenaDetails: {
            flying: {
                type: 'effortless',
                altitude: 'cloud_level',
            },
        },
        quality: 8,
        clarity: 9,
        moodAfter: 9,
        timeOfDay: 'night',
        visualStyle: 'vivid',
        perspective: 'first_person',
        roles: ['protagonist'],
        sensations: ['sounds', 'tactile', 'kinesthetic'],
        characters: ['Незнакомец в черном'],
        locations: ['Заброшенный город', 'Небо'],
        objects: ['Высотки', 'Разрушенный мост'],
        emotions: ['Восторг', 'Свобода', 'Спокойствие'],

        PreSleepContext: 'Пил вечером крепкий мате и читал перед сном.',
        interpretations: [
            {
                tag: 'Полет',
                meaning:
                    'Стремление вырваться из повседневной рутины или чувство контроля над ситуацией.',
                sourceId: 'base_guide',
                isAccurate: true,
            },
        ],
        personalNotes: 'Нужно попробовать в следующий раз в ОС вызвать конкретного человека.',
        isFavorite: true,
        isPinned: true,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 2. Кошмар с падением, физической реакцией и историей связей
    {
        date: '2026-08-03',
        title: 'Бесконечные коридоры старой фабрики',
        description:
            'Заблудился среди печатных станков и сушильных камер. Коридоры бесконечно петляли, а гул оборудования становился оглушительным. Оступился на мостике и сорвался вниз.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 7,
                copingMechanism: 'Проснулся от судороги в ноге',
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['falling'],
        phenomenaDetails: {
            falling: {
                origin: 'building_or_cliff',
                outcome: 'hypnic_jerk',
            },
        },
        quality: 4,
        clarity: 6,
        moodAfter: 3,
        timeOfDay: 'night',
        visualStyle: 'monochrome',
        perspective: 'first_person',
        roles: ['victim'],
        sensations: ['sounds', 'breathing', 'tactile'],
        characters: ['Служебная тень'],
        locations: ['Цех', 'Бесконечный коридор'],
        objects: ['Печатный станок', 'Сушильная камера'],
        emotions: ['Тревога', 'Страх', 'Растерянность'],

        PreSleepContext: 'Тяжелая смена на печатном производстве, усталость.',
        relatedDreams: [
            {
                relationType: 'recurring_instance',
                note: 'Повторяющийся сюжет с заплутанием в производственных помещениях.',
            },
        ],
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 3. Вещий сон (Prophetic) с неопределенным статусом исполнения и таймлайном
    {
        date: '2026-08-05',
        title: 'Разговор у старого маяка на испанском',
        description:
            'Сидели на краю обрыва возле старого маяка и вели беседу. Остро ощущался запах соли, а речь звучала исключительно на беглом испанском языке.',
        categories: ['prophetic'],
        categoryDetails: {
            prophetic: {
                expectedByDate: '2026-10-15',
                isFulfilled: false,
            },
        },
        quality: 9,
        clarity: 10,
        moodAfter: 8,
        timeOfDay: 'morning',
        visualStyle: 'color',
        perspective: 'first_person',
        roles: ['protagonist', 'observer'],
        sensations: ['sounds', 'smells', 'tactile', 'temperature', 'speech_voice'],
        characters: ['Старик-смотритель'],
        locations: ['Маяк', 'Морской обрыв'],
        objects: ['Фонарь', 'Деревянная скамья'],
        emotions: ['Умиротворение', 'Ностальгия'],

        interpretations: [
            {
                tag: 'Маяк',
                meaning: 'Поиск верного ориентира или долгожданное решение сложного вопроса.',
                sourceId: 'custom',
                isAccurate: null,
            },
        ],
        relatedDreams: [
            {
                dreamId: 1,
                relationType: 'similar_theme',
                note: 'Похожее ощущение высоты и ветра.',
            },
        ],
        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 4. Локация/Сюжет с древней мифологией и аномалиями зрения (Без категорий)
    {
        date: '2026-08-06',
        title: 'Античный амфитеатр и руины Олимпа',
        description:
            'Бродил по древнегреческому амфитеатру под палящим солнцем. На ступенях лежали пергаменты с надписями на древнегреческом. Вся картинка переливалась странными инвертированными цветами.',
        categories: [],
        quality: 7,
        clarity: 8,
        moodAfter: 7,
        timeOfDay: 'day',
        visualStyle: 'vivid',
        perspective: 'third_person',
        roles: ['observer', 'camera_operator'],
        sensations: ['sounds', 'temperature', 'vision_anomaly'],
        characters: ['Оратор в тоге'],
        locations: ['Амфитеатр', 'Древние руины'],
        objects: ['Свитков пергамента', 'Каменные колонны'],
        emotions: ['Любопытство', 'Удивление'],

        PreSleepContext: 'Разбирал грамматические структуры текста вечером.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 5. Двойной феномен (Falling + Death) в духе Dark Fantasy / Sci-Fi
    {
        date: '2026-08-07',
        title: 'Песчаная буря и падение с цитадели',
        description:
            'Гигантская песчаная стена накрывала древний город. Я стоял на вершине башни, оступился и полетел вниз. После удара наступила полная тишина и темнота, но я продолжал осознавать себя.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 8,
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['falling', 'death'],
        phenomenaDetails: {
            falling: {
                origin: 'building_or_cliff',
                outcome: 'impact',
            },
            death: {
                cause: 'fall',
                aftermath: 'black_void',
            },
        },
        quality: 5,
        clarity: 8,
        moodAfter: 5,
        timeOfDay: 'night',
        visualStyle: 'dark',
        perspective: 'first_person',
        roles: ['victim', 'disembodied'],
        sensations: ['sounds', 'tactile', 'pain'],
        characters: ['Безымянный страж'],
        locations: ['Цитадель', 'Пустыня'],
        objects: ['Каменный парапет', 'Песчаные часы'],
        emotions: ['Напряжение', 'Замирание', 'Фатализм'],

        PreSleepContext: 'Перечитывал главу фэнтези перед сном.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 6. Люцидный подводный мир (ОС) с сильной физиологией
    {
        date: '2026-08-08',
        title: 'Погружение в жеоду и светящиеся минералы',
        description:
            'Оказался внутри гигантской кристальной пещеры. Стены состояли из аметистов и кварца, излучающих холодный фиолетовый свет. Вспомнил про проверку реальности и начал исследовать структуры кристаллов руками.',
        categories: ['lucid'],
        categoryDetails: {
            lucid: {
                controlLevel: 9,
                trigger: 'reality_check',
            },
        },
        quality: 10,
        clarity: 10,
        moodAfter: 10,
        timeOfDay: 'morning',
        visualStyle: 'vivid',
        perspective: 'first_person',
        roles: ['protagonist'],
        sensations: ['tactile', 'temperature', 'vision_anomaly'],
        characters: [],
        locations: ['Кристальная пещера', 'Подземелье'],
        objects: ['Аметистовый друза', 'Пегматит'],
        emotions: ['Восторг', 'Исследование', 'Восхищение'],
        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 7. Сон-черновик (isDraft: true) с редкими свойствами
    {
        date: '2026-08-08',
        title: 'Акустический концерт хэви-метала на холме',
        description:
            'Зарисовка: Стадион под открытым небом, классический мощный звук, гитарные соло звучали невероятно объемно. Выполнял роль видеооператора с камерой.',
        categories: [],
        quality: 6,
        clarity: 6,
        moodAfter: 7,
        timeOfDay: 'evening',
        visualStyle: 'color',
        perspective: 'third_person',
        roles: ['camera_operator', 'observer'],
        sensations: ['sounds', 'kinesthetic'],
        characters: ['Музыканты'],
        locations: ['Открытая арена', 'Холм'],
        objects: ['Гитарный стеку', 'Микрофон'],
        emotions: ['Драйв', 'Энергия'],

        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: true,
        isPrivate: true,
    },

    // 8. Сонный паралич (Paralysis)
    {
        date: '2026-08-09',
        title: 'Ночной сонный паралич и тяжелый гул',
        description:
            'Проснулся, но тело полностью отказаться подчиняться. Слышал отчетливый низкочастотный гул и ощущал чье-то присутствие в углу комнаты.',
        categories: ['nightmare'],
        categoryDetails: {
            nightmare: {
                fearLevel: 9,
                hasPhysicalResponse: true,
            },
        },
        phenomena: ['paralysis'],
        phenomenaDetails: {
            paralysis: {
                timing: 'waking_up',
                hallucinations: ['auditory', 'presence'],
            },
        },
        quality: 3,
        clarity: 8,
        moodAfter: 3,
        timeOfDay: 'morning',
        visualStyle: 'dark',
        perspective: 'first_person',
        roles: ['victim'],
        sensations: ['sounds', 'speech_voice', 'tactile'],
        characters: ['Теневая фигура'],
        locations: ['Спальня'],
        objects: ['Кровать'],
        emotions: ['Паника', 'Оцепенение'],

        PreSleepContext: 'Устал за день, уснул на спине.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },

    // 9. Вложенный сон / Ложное пробуждение (Nested Dream)
    {
        date: '2026-08-09',
        title: 'Ложное пробуждение и поиски ключей',
        description:
            'Проснулся, встал с кровати, заварил мате, а потом понял, что часы идут в обратную сторону. «Проснулся» второй раз — снова в кровати. Двойной слой пробуждения.',
        categories: [],
        phenomena: ['nested_dream'],
        phenomenaDetails: {
            nestedDream: {
                nestingLevels: 2,
            },
        },
        quality: 7,
        clarity: 8,
        moodAfter: 6,
        timeOfDay: 'morning',
        visualStyle: 'color',
        perspective: 'first_person',
        roles: ['protagonist'],
        sensations: ['taste', 'tactile', 'sounds'],
        characters: [],
        locations: ['Дом', 'Кухня'],
        objects: ['Калебас', 'Бомбилья', 'Настенные часы'],
        emotions: ['Замешательство', 'Интрига'],

        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
];
