import type { DreamWrite } from '@/types/Dream';

export const initialDreamsSeed: DreamWrite[] = [
    {
        date: '2026-08-01',
        title: 'Заброшенный город и полеты',
        description:
            'Летал над заброшенным мегаполисом. В какой-то момент понял, что это сон, и попробовал управлять высотой полета. Ветер ощущался очень реально.',
        categories: ['lucid'],
        quality: 8,
        clarity: 9,
        lucidityLevel: 7,
        moodAfter: 9,
        timeOfDay: 'night',
        isColor: true,
        sensations: ['sounds', 'tactile'],
        characters: ['Незнакомец в черном'],
        locations: ['Заброшенный город', 'Небо'],
        objects: ['Высотки', 'Разрушенный мост'],
        emotions: ['Восторг', 'Свобода', 'Спокойствие'],
        tags: ['полет', 'осознанность', 'город'],
        PreSleepContext: 'Пила вечером крепкий мате и читала перед сном.',
        interpretations: [
            {
                symbol: 'Полет',
                meaning:
                    'Стремление вырваться из повседневной рутины или чувство контроля над ситуацией.',
                source: 'base_guide',
            },
        ],
        personalNotes: 'Нужно попробовать в следующий раз в ОС вызвать конкретного человека.',
        isFavorite: true,
        isPinned: true,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-03',
        title: 'Бесконечный лабиринт в школе',
        description:
            'Снова оказался в своей старой школе, но коридоры бесконечно петляли и меняли форму. Пытался найти выход на экзамен.',
        categories: ['recurring', 'nightmare'],
        quality: 4,
        clarity: 6,
        moodAfter: 3,
        timeOfDay: 'night',
        isColor: false,
        sensations: ['sounds'],
        characters: ['Учитель математики', 'Одноклассники'],
        locations: ['Школа', 'Темный коридор'],
        objects: ['Закрытая дверь', 'Часы'],
        emotions: ['Тревога', 'Страх', 'Растерянность'],
        tags: ['школа', 'коридоры', 'экзамен'],
        PreSleepContext: 'Тяжелый рабочий день, переживал из-за дедлайна.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-05',
        title: 'Разговор у старого маяка',
        description:
            'Сидели на краю обрыва возле старого маяка и слушали шум прибоя. Запах соли был настолько сильным, будто я реально стоял у моря.',
        categories: ['prophetic'],
        quality: 9,
        clarity: 10,
        moodAfter: 8,
        timeOfDay: 'morning',
        isColor: true,
        sensations: ['sounds', 'smells', 'tactile'],
        characters: ['Старик-смотритель'],
        locations: ['Маяк', 'Морское побережье'],
        objects: ['Фонарь', 'Деревянная скамья'],
        emotions: ['Умиротворение', 'Ностальгия'],
        tags: ['море', 'маяк', 'беседа'],
        interpretations: [
            {
                symbol: 'Маяк',
                meaning: 'Поиск верного пути или ориентира в жизни.',
                source: 'custom',
            },
        ],
        relatedDreams: [
            {
                dreamId: 1,
                relationType: 'similar_theme',
            },
        ],
        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-06',
        title: 'Затерянная библиотека и гигантские песочные часы',
        description:
            'Ходил по многоэтажной библиотеке, где вместо лестниц были парящие деревянные ступени. В центре зала стояли песочные часы высотой с дом, и песок в них сыпался вверх.',
        categories: ['normal'],
        quality: 7,
        clarity: 8,
        moodAfter: 7,
        timeOfDay: 'night',
        isColor: true,
        sensations: ['sounds', 'tactile'],
        characters: ['Библиотекарь в маске'],
        locations: ['Древняя библиотека', 'Парящие лестницы'],
        objects: ['Старинные фолианты', 'Песочные часы'],
        emotions: ['Любопытство', 'Удивление'],
        tags: ['библиотека', 'книги', 'время', 'магия'],
        PreSleepContext: 'Слушал фоновую эмбиент-музыку перед сном.',
        interpretations: [
            {
                symbol: 'Часы',
                meaning: 'Осознание ценности времени или переживания о нехватке ресурса.',
                source: 'base_guide',
            },
        ],
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-07',
        title: 'Погоня в неоновом дождовом городе',
        description:
            'Убегал от странных теней по узким улочкам неонового сити в стиле киберпанка. Асфальт блестел от луж, а сверху доносился гул пролетающих машин.',
        categories: ['nightmare'],
        quality: 5,
        clarity: 7,
        moodAfter: 4,
        timeOfDay: 'night',
        isColor: true,
        sensations: ['sounds', 'tactile'],
        characters: ['Теневые силуэты'],
        locations: ['Неоновый город', 'Темные переулки'],
        objects: ['Затопленные лужи', 'Яркие вывески'],
        emotions: ['Напряжение', 'Азарт', 'Страх'],
        tags: ['погоня', 'неон', 'киберпанк', 'дождь'],
        PreSleepContext: 'Поздно заснул после просмотра нуарного фильма.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-08',
        title: 'Подводный сад и светящиеся рыбы',
        description:
            'Плавательное погружение без акваланга. Мог свободно дышать под водой. Вокруг цвели гигантские подводные растения, а мелкие рыбы светились бирюзовым светом при прикосновении.',
        categories: ['lucid', 'normal'],
        quality: 10,
        clarity: 9,
        lucidityLevel: 5,
        moodAfter: 10,
        timeOfDay: 'morning',
        isColor: true,
        sensations: ['tactile'],
        characters: [],
        locations: ['Подводный сад', 'Океанское дно'],
        objects: ['Светящиеся водоросли', 'Коралловый риф'],
        emotions: ['Восторг', 'Спокойствие', 'Гармония'],
        tags: ['вода', 'океан', 'дыхание', 'природа'],
        isFavorite: true,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
    {
        date: '2026-08-08',
        title: 'Странная поездка на ночном поезде',
        description:
            'Черновик: ехал в поезде, который двигался без рельсов прямо по заснеженному полю. За окном мелькали только редкие одинокие фонари.',
        categories: ['normal'],
        quality: 6,
        clarity: 5,
        moodAfter: 5,
        timeOfDay: 'nap',
        isColor: false,
        sensations: ['sounds'],
        characters: ['Пассажир напротив'],
        locations: ['Купе поезда', 'Заснеженное поле'],
        objects: ['Стакан в подстаканнике', 'Фонарь'],
        emotions: ['Одиночество', 'Задумчивость'],
        tags: ['поезд', 'снег', 'дорога'],
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: true, // Помечен как черновик для проверки фильтра скетчей
        isPrivate: true,
    },
    {
        date: '2026-08-08',
        title: 'Шепот старого леса',
        description:
            'Гулял по туманному хвойному лесу. Деревья тихо издавали звуки, похожие на людской шепот, но было не страшно, а скорее загадочно.',
        categories: ['prophetic'],
        quality: 8,
        clarity: 7,
        moodAfter: 8,
        timeOfDay: 'nap',
        isColor: true,
        sensations: ['sounds', 'smells'],
        characters: [],
        locations: ['Хвойный лес', 'Туманная поляна'],
        objects: ['Старый пень', 'Мал'],
        emotions: ['Таинственность', 'Умиротворение'],
        tags: ['лес', 'туман', 'природа', 'шепот'],
        PreSleepContext: 'Гулял вечером на свежем воздухе.',
        isFavorite: false,
        isPinned: false,
        isArchived: false,
        isDeleted: false,
        isDraft: false,
        isPrivate: true,
    },
];
