import type { InterprSourceWrite } from '@/services/schemas/interpretationSource.schema';

export const initialSourcesSeed: (InterprSourceWrite & { id: string })[] = [
    {
        id: 'mine',
        title: 'Мой личный сонник',
        authorName: 'Собственные записи',
        description:
            'Персональный архив толкований, личных ассоциаций и дневниковых наблюдений, не привязанных к внешним источникам.',
        rating: 5.0,
        type: 'custom',
        category: 'personal',
        visibility: 'private',
        isEditable: true,
        usersCount: 1,
        iconName: 'UserCheck',
    },
    {
        id: 'miller',
        title: 'Сонник Миллера',
        authorName: 'Густавус Хайндман Миллер',
        description:
            'Классический системный сонник конца XIX века. Упор на практические жизненные предсказания и бытовые знаки.',
        rating: 4.8,
        type: 'system',
        category: 'esoteric',
        visibility: 'public',
        isEditable: false,
        usersCount: 1500,
        iconName: 'BookOpen',
    },
    {
        id: 'freud',
        title: 'Сонник Фрейда',
        authorName: 'Зигмунд Фрейд',
        description:
            'Психоаналитический подход. Толкование через подавленные желания, бессознательное и ассоциативные связи.',
        rating: 4.5,
        type: 'author',
        category: 'psychology',
        visibility: 'public',
        isEditable: false,
        usersCount: 1200,
        iconName: 'Brain',
    },
    {
        id: 'jung',
        title: 'Архетипы Юнга',
        authorName: 'Карл Густав Юнг',
        description:
            'Глубинная психология: анализ сновидений через коллективное бессознательное, архетипы (Тень, Анима, Мудрец) и мифологемы.',
        rating: 4.9,
        type: 'author',
        category: 'psychology',
        visibility: 'public',
        isEditable: false,
        usersCount: 980,
        iconName: 'Sparkles',
    },
    {
        id: 'loff',
        title: 'Сонник Лоффа',
        authorName: 'Дэвид Лофф',
        description:
            'Современный психотерапевтический подход: акцент на индивидуальном жизненном контексте и сценариях сновидца.',
        rating: 4.7,
        type: 'author',
        category: 'psychology',
        visibility: 'public',
        isEditable: false,
        usersCount: 850,
        iconName: 'UserCheck',
    },
    {
        id: 'vanga',
        title: 'Сонник Ванги',
        authorName: 'Вангелия Гуштерова (Ванга)',
        description:
            'Традиционные эзотерические толкования с акцентом на судьбоносные знаки, предупреждения и духовный путь.',
        rating: 4.6,
        type: 'author',
        category: 'esoteric',
        visibility: 'public',
        isEditable: false,
        usersCount: 1100,
        iconName: 'Eye',
    },
    {
        id: 'veles',
        title: 'Малый Велесов сонник',
        authorName: 'Народная традиция',
        description:
            'Славянский фольклорный сонник. Толкование через стихии, бытовые народные приметы и языческие архетипы.',
        rating: 4.4,
        type: 'system',
        category: 'cultural',
        visibility: 'public',
        isEditable: false,
        usersCount: 620,
        iconName: 'Flame',
    },
    {
        id: 'aesop',
        title: 'Сонник Эзопа',
        authorName: 'Народные метафоры / Эзоп',
        description:
            'Интерпретация образов через фразеологизмы, идиомы, пословицы и басенные аллегории («медвежья услуга», «волк в овечьей шкуре»).',
        rating: 4.3,
        type: 'author',
        category: 'cultural',
        visibility: 'public',
        isEditable: false,
        usersCount: 450,
        iconName: 'Quote',
    },
];
